zookeeper:
    image: jplock/zookeeper:3.4.11
    container_name: zookeeper
    ports:
        - 2181:2181


kafka:
    image: ches/kafka:0.10.2.1
    container_name: kafka
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ZHOST}
        - ZOOKEEPER_IP=${KAFKA_ZHOST}
    ports:
        - 7203:7203
        - 9092:9092


elassandra:
    image: erangaeb/elassandra:4.0
    container_name: elassandra
    environment:
        - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
        - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
    volumes:
        ['$CASSANDRA_DATA_DIR:/opt/cassandra/data']
    ports:
        - 7000:7000
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
        - 9200:9200
        - 9300:9300


airtrafficrest:
    image: supunucsc/airtrafficrest:0.1
    container_name: airtrafficrest
    environment:
        - SENZIE_NAME=${REST_NAME}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$REST_LOGS_DIR:/app/logs', '$REST_KEYS_DIR:/app/.keys']
    ports:
        - 7070:7070


oemchain:
    image: erangaeb/3chain:0.1
    container_name: oemchain
    environment:
        - SENZIE_NAME=${OEMCHAIN_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
        - KAFKA_TOPIC=${OEMCHAIN_KAFKA_TOPIC}
        - KAFKA_CGROUP=${OEMCHAIN_KAFKA_CGROUP}
        - PO_API=${PO_API}
        - PRNT_API=${PRNT_API}
    volumes:
        ['$OEMCHAIN_LOGS_DIR:/app/logs', '$OEMCHAIN_KEYS_DIR:/app/.keys']


amcchain:
    image: erangaeb/3chain:0.1
    container_name: amcchain
    environment:
        - SENZIE_NAME=${AMCCHAIN_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
        - KAFKA_TOPIC=${AMCCHAIN_KAFKA_TOPIC}
        - KAFKA_CGROUP=${AMCCHAIN_KAFKA_CGROUP}
        - PO_API=${PO_API}
        - PRNT_API=${PRNT_API}
    volumes:
        ['$AMCCHAIN_LOGS_DIR:/app/logs', '$AMCCHAIN_KEYS_DIR:/app/.keys']


3ops:
    image: erangaeb/3ops:0.1
    container_name: 3ops
    environment:
        - SENZIE_NAME=${OPS_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
        - PR_API=${PR_API}
        - PO_API=${PO_API}
        - PRNT_API=${PRNT_API}
    volumes:
        ['$OPS_LOGS_DIR:/app/logs', '$OPS_KEYS_DIR:/app/.keys']


3miner:
    image: erangaeb/3miner:0.1
    container_name: 3miner
    environment:
        - SENZIE_NAME=${MINER_NAME}
        - MINING_INTERVAL=${MINING_INTERVAL}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - ELASTIC_CLUSTER=${ELASTIC_CLUSTER}
        - ELASTIC_HOST=${ELASTIC_HOST}
        - ELASTIC_PORT=${ELASTIC_PORT}
        - KAFKA_HOST=${KAFKA_HOST}
        - KAFKA_PORT=${KAFKA_PORT}
    volumes:
        ['$MINER_LOGS_DIR:/app/logs', '$MINER_KEYS_DIR:/app/.keys']


dazh:
    image: supunucsc/kafkaclient:0.1
    container_name: dazh
    environment:
        - KAFKA_HOSTIP=${KAFKA_HOST}
        - KAFKA_PORT=${KAFKA_PORT}
        - KAFKA_TOPIC_TRANS=tranz
        - KAFKA_TOPIC_BLOCKS=blockz
        - WEBSOCKET_PORT=10000
    ports:
        - 10000:10000


webm:
    image: supunucsc/webmiddleware:0.1
    container_name: webm
    environment:
        - ELASTICSEARCH_HOST=${ELASTIC_HOST}
        - ELASTICSEARCH_PORT=9200
        - API_PORT=5000
    ports:
        - 5000:5000


webz:
    image: supunucsc/blockchainfrontend:0.3
    container_name: webz
    environment:
        - REACT_APP_WEBM_PORT=5000
        - REACT_APP_WEBM_HOST=13.250.38.208
        - REACT_APP_WEBSOCKET_HOST=13.250.38.208
        - REACT_APP_WEBSOCKET_PORT=10000
    ports:
        - 3000:3000
